apiVersion: v1 # string
kind: Pod # sting
metadata: # Dictionary of pod
  name: myapp-pod
  labels:
    app: myapp

spec:
  containers: # list
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80
